ワーキングアグリーメントに障害発生時の対応についての項目を追加
lifestyledesign/README pull request #1
Opened 2021-06-21 11:05 UTC by tkan1227

ワーキングアグリーメントに障害発生時の対応についての項目を追加しました。

2021-06-22 03:45 UTC, stakahashi requested changes
もう少し簡潔にできると良いかと思います

>  障害対応で緊急を要するものはOncallとして処理する

この件はちょっと分かりにくいですね。 障害 = OnCall みたいなものなのでよく分からない感じになっちゃってます

> 緊急対応に該当しないものに関しては、Clickupにチケットを追加し、スプリント外のタスクとして対応する

内容によってはスプリントに入れるべき内容だと思うのでスプリント外では無いと思います。

2021-06-23 05:09 UTC, tkan1227 commented
@stakahashi コメントいただいた箇所修正しましたー

2021-06-24 06:07 UTC, stakahashi approved these changes
LGTM

2021-06-24 06:08 UTC, stakahashi commented on team-working-agreement.md
> +    - oncallの対応はプロダクト部のエンジニアが一週間ごとに交代制で担当する
```suggestion
    - OnCallの対応はプロダクト部のエンジニアが一週間ごとに交代制で担当する
```

2021-06-28 05:04 UTC, merged